# Generated by Django 5.2.6 on 2025-09-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_alter_vehiculo_año'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(default='Sin Descripción', max_length=500),
        ),
        migrations.AlterField(
            model_name='ordenreparacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
